name: Purge BunnyCDN Cache

on:
  workflow_dispatch:

jobs:
  purge-bunny-cache:
    runs-on: ubuntu-latest

    env:
      BUNNY_API_KEY: ${{ secrets.BUNNY_API_KEY }}
      PURGE_URL: https://qa-metrics.conholdate.cloud
      AWS_ACCESS_KEY_ID: ${{ secrets.CEPH_S3_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CEPH_S3_SECRET_KEY }}
      AWS_DEFAULT_REGION: us-east-1
      AWS_ENDPOINT_URL: https://s3-admin-qa.dynabic.com
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}

    steps:
      - name: Purge BunnyCDN Cache
        run: |
          echo "Purging cache for $PURGE_URL"
          curl -siG \
            -H "X-Api-Key: $BUNNY_API_KEY" \
            --data-urlencode "url=$PURGE_URL" \
            "https://api.dynabic.com/bn/purge?async=true"
